[package]
name = "lume-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
lume-adaptrix = { path = "../lume-adaptrix" }
tobj = "4.0"
bytemuck = { version = "1.14", features = ["derive"] }
anyhow = "1.0"
bincode = "1.3"
log = "0.4"
env_logger = "0.10"
meshopt = "0.1.9"
