[package]
name = "lume-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
lume-adaptrix = { path = "../lume-adaptrix" }
meshopt = "0.6"
tobj = "4.0"
glam = "0.24"
bytemuck = { version = "1.14", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
